name: SSH 登录

on:
  schedule:
    - cron: '0 11 5 * *'  # 每月5号北京时间19点运行（UTC+8）
  workflow_dispatch:  # 开启手动触发

jobs:
  ssh-login-job:
    runs-on: ubuntu-latest
    steps:
      - name: 检出存储库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install paramiko requests

      - name: 运行 Python 脚本
        env:
          SSH_INFO: ${{ secrets.SSH_INFO }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          MAIL: ${{ secrets.MAIL }}
          PUSH: ${{ secrets.PUSH }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python run.py

